on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
    - uses: actions/checkout@master
      with:
        url: "https://jenkins.thecman.xyz"
        user: "escadmin"
        token: "11d58ff67fd0fef6edfed38130d5826736"
        job: "EtherscanV3Design"
